In [1]:
#import 
import math 

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [2]:
# math 모듈에 있는 기능
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [3]:
print('pi의 값을 4자리 = {:.4}'.format(math.pi))

pi의 값을 4자리 = 3.142


In [4]:
math.log(32,3) 

3.154648767857287

In [5]:
#math를 mt로 지정
import math as mt 
mt.pi

3.141592653589793

In [6]:
#math 모듈에 있는 모든 기능 사용하겠다
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


In [7]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [10]:
import numpy as np 
rolls = np.random.randint(low=1, high=6, size=10)
rolls
# 1-6사이의 숫자에서 랜덤으로 1개의 숫자만 10개 뽑아줘 

array([4, 2, 4, 2, 5, 3, 5, 3, 1, 2])

In [12]:
xlist = [[1,2,3],[2,4,6],]
x = np.asarray(xlist)

print("xlist = {}\nx =\n{}".format(xlist, x))
# array (기본값으로) 객체의 복사본을 생성하지만, asarray 는 필요하지 않을 때는 생성하지 않는다

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [16]:
type(xlist)

list

In [14]:
type(x)

numpy.ndarray

In [13]:
x[1,-1]
# x에서 1번째 리스트에 있는 -1번째의 값 
# 다차원 데이터

6

In [18]:
xlist[1][-1]

6

In [1]:
import tensorflow as tf
# Create two constants, each with value 1
a = tf.constant(1)
b = tf.constant(1)
# Add them together to get...
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>